on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload files to /var/www/test-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ SERVER_HOST }}
          username: ${{ SERVER_USER }}
          key: ${{ SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/var/www/test-server"
          strip_components: 0


